require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/application.rb'
    - 'config/environments/*.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
  TargetRubyVersion: 3.2.4

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 140

Layout/LineLength:
  Max: 130
